-- ----- generated by the dockyrs installer -----
local mainMod = _G.mainMod or "SUPER"
local dockyrs = "/home/fedi41/Packages/Docky.rs/target/release/dockyrs"

hl.on("hyprland.start", function()
    hl.exec_cmd(dockyrs)
    hl.exec_cmd("/home/fedi41/Packages/Docky.rs/target/release/dockyrs-notifyd")
    hl.exec_cmd("/home/fedi41/Packages/Docky.rs/restore-wallpaper.sh")
end)

hl.bind(mainMod .. " + D", hl.dsp.exec_cmd(dockyrs .. " --toggle-search"))
hl.bind(mainMod .. " + W", hl.dsp.exec_cmd(dockyrs .. " --toggle-wallpaper"))
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd(dockyrs .. " --toggle-clipboard"))
hl.bind(mainMod .. " + comma", hl.dsp.exec_cmd(dockyrs .. " --toggle-dock-menu"))
hl.bind("F8", hl.dsp.exec_cmd(dockyrs .. " --screenshot-region"))
hl.bind("F9", hl.dsp.exec_cmd(dockyrs .. " --screenshot-full"))
hl.bind(mainMod .. " + SHIFT + CTRL + 1", hl.dsp.exec_cmd(dockyrs .. " --test-notification"))
hl.bind("F10", hl.dsp.exec_cmd("/home/fedi41/Packages/Docky.rs/record-toggle.sh"), { locked = true })
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd("/home/fedi41/Packages/Docky.rs/relaunch.sh"))
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 1%+ && " .. dockyrs .. " --osd-volume"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 1%- && " .. dockyrs .. " --osd-volume"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && " .. dockyrs .. " --osd-volume"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })
hl.bind("code:225", hl.dsp.exec_cmd("brightnessctl -n2 set 1%+ && " .. dockyrs .. " --osd-brightness"), { locked = true, repeating = true })
hl.bind("code:224", hl.dsp.exec_cmd("brightnessctl -n2 set 1%- && " .. dockyrs .. " --osd-brightness"), { locked = true, repeating = true })

hl.layer_rule({
    name  = "dockyrs-blur",
    match = { namespace = "^dockyrs(-menu)?$" },
    blur         = true,
    ignore_alpha = 0.0,
})
